import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PillBase } from "@/components/ui/3d-adaptive-navigation-bar";
import { SmoothScrollProvider } from "@/components/providers/smooth-scroll-provider";
import { KineticCursor } from "@/components/ui/kinetic-cursor";

const grotesk = localFont({
  src: [
    {
      path: "./fonts/Grotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk-DemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={grotesk.variable}>
      <body className="antialiased font-sans">
        <SmoothScrollProvider>
          <KineticCursor />
          <header className="fixed top-6 left-1/2 -translate-x-1/2 z-50">
            <PillBase />
          </header>
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
