import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SmoothScrollProvider } from "@/components/providers/smooth-scroll-provider";
import { ConditionalLayout } from "@/components/conditional-layout";

const grotesk = localFont({
  src: [
    {
      path: "./fonts/Grotesk-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk-DemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Grotesk-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-grotesk",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={grotesk.variable}>
      <body className="antialiased font-sans">
        <SmoothScrollProvider>
          <ConditionalLayout />
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
