export const eventsData = {
  movies_and_dramatics: [
    {
      id: 1,
      format: "Stageplay",
      title: "Broadway Chronicles",
      description:
        "A full-length dramatic performance with storyline and dialogues.",
      is_srm_only: false,
    },
    {
      id: 2,
      format: "Streetplay",
      title: "Nukkad Natak",
      description:
        "Street performance addressing a social issue without props.",
      is_srm_only: false,
    },
    {
      id: 3,
      format: "Monologue",
      title: "Solo Saga",
      description: "Solo dramatic performance expressing a single character.",
      is_srm_only: true,
    },
    {
      id: 4,
      format: "Script Writing",
      title: "Ink & Imagination",
      description: "Write an original script based on a given theme.",
      is_srm_only: true,
    },
    {
      id: 5,
      format: "Short Film",
      title: "CineFest",
      description: "Submit an original short film of any genre.",
      is_srm_only: false,
    },
    {
      id: 6,
      format: "Mime",
      title: "Mime",
      description: "Silent theatrical art using expressions and movement.",
      is_srm_only: false,
    },
    {
      id: 7,
      format: "Adzap",
      title: "Adzap",
      description:
        "Create a humorous advertisement skit for an imaginary product.",
      is_srm_only: false,
    },
  ],
  creative_arts: [
    {
      id: 8,
      format: "Character Design",
      title: "Character Roulette",
      description: "Draw a character based on a random prompt.",
      is_srm_only: true,
    },
    {
      id: 9,
      format: "Sketching",
      title: "Sketch It Out",
      description: "Pencil sketching based on theme.",
      is_srm_only: false,
    },
    {
      id: 10,
      format: "Crafts",
      title: "Best Out of Waste",
      description: "Create art entirely from waste materials.",
      is_srm_only: false,
    },
    {
      id: 11,
      format: "Graphic Design",
      title: "Design.exe",
      description: "Digital graphical designing event.",
      is_srm_only: true,
    },
    {
      id: 12,
      format: "Digital Art",
      title: "Metamorphic Art",
      description: "Transform a reference image creatively.",
      is_srm_only: false,
    },
  ],
  music: [
    {
      id: 13,
      format: "Band (Eastern)",
      title: "Eastern Unbound",
      description: "Eastern/regional style band competition.",
      is_srm_only: false,
    },
    {
      id: 14,
      format: "Band (Western)",
      title: "Western Unbound",
      description: "Western/English music band competition.",
      is_srm_only: false,
    },
    {
      id: 15,
      format: "Rap",
      title: "Barz & Bass: Rap",
      description: "Rap performance showcasing rhythm and flow.",
      is_srm_only: true,
    },
    {
      id: 16,
      format: "Beatbox",
      title: "Barz & Bass: Beatbox",
      description: "Live beatboxing performance.",
      is_srm_only: true,
    },
    {
      id: 17,
      format: "Instrumental",
      title: "Crescendo",
      description: "Solo instrumental performance.",
      is_srm_only: false,
    },
    {
      id: 18,
      format: "Vocal Solo",
      title: "Echoverse",
      description: "Western/English solo singing.",
      is_srm_only: true,
    },
    {
      id: 19,
      format: "Vocal Classical",
      title: "Swarnajali",
      description: "Classical Eastern vocal performance.",
      is_srm_only: false,
    },
  ],
  dance: [
    {
      id: 20,
      format: "Solo Dance",
      title: "Kinetix",
      description: "Solo western dance performance.",
      is_srm_only: false,
    },
    {
      id: 21,
      format: "Battle",
      title: "Urban Showdown",
      description: "1v1 street dance battle.",
      is_srm_only: true,
    },
    {
      id: 22,
      format: "Group Dance",
      title: "Choreonite",
      description: "Western group/crew dance performance.",
      is_srm_only: false,
    },
    {
      id: 23,
      format: "Classical",
      title: "Rasadhara",
      description: "Classical dance solo performance.",
      is_srm_only: true,
    },
    {
      id: 24,
      format: "Thematic",
      title: "Fuzzon",
      description: "Creative choreography conveying a message.",
      is_srm_only: false,
    },
    {
      id: 25,
      format: "Folk",
      title: "Parampara",
      description: "Tribal / Native Folk dance performance.",
      is_srm_only: false,
    },
  ],
  fashion: [
    {
      id: 26,
      format: "Runway",
      title: "En Vogue Demain",
      description: "Inter-college runway fashion competition.",
      is_srm_only: false,
    },
    {
      id: 27,
      format: "Pageant",
      title: "Mr. & Miss. Milan",
      description: "Personality and style pageant with self-made costumes.",
      is_srm_only: true,
    },
  ],
  astrophilia: [
    {
      id: 28,
      format: "Hackathon",
      title: "Hack the Stars",
      description: "Prototype and pitch innovative space-tech concepts.",
      is_srm_only: true,
    },
    {
      id: 29,
      format: "Case Study",
      title: "Space Odyssey",
      description: "Design a hypothetical space mission.",
      is_srm_only: true,
    },
  ],
  literary: [
    {
      id: 30,
      format: "Improv Debate",
      title: "Shipwreck",
      description: "Character-based comedic debate for survival.",
      is_srm_only: false,
    },
    {
      id: 31,
      format: "Poetry",
      title: "Slam Poetry",
      description: "Write and perform poetry based on a prompt.",
      is_srm_only: true,
    },
    {
      id: 32,
      format: "Debate",
      title: "Debate",
      description: "Team-based debate with rebuttals.",
      is_srm_only: false,
    },
    {
      id: 33,
      format: "Speaking",
      title: "JAM (Just A Minute)",
      description: "One-minute speaking challenge with no pauses or errors.",
      is_srm_only: false,
    },
  ],
  self_defense: [
    {
      id: 34,
      format: "Combat",
      title: "Kick Boxing",
      description: "Kick Boxing Competition.",
      is_srm_only: true,
    },
    {
      id: 35,
      format: "Combat",
      title: "Boxing",
      description: "Competitive boxing event.",
      is_srm_only: true,
    },
  ],
  gaming: [
    {
      id: 36,
      format: "Quiz",
      title: "Trivia Quiz",
      description: "General knowledge quiz contest.",
      is_srm_only: true,
    },
    {
      id: 37,
      format: "Console",
      title: "e-Football",
      description: "1v1 football gaming match.",
      is_srm_only: true,
    },
    {
      id: 38,
      format: "Mobile",
      title: "BGMI",
      description: "4v4 mobile battle royale tournament.",
      is_srm_only: false,
    },
    {
      id: 39,
      format: "Mobile",
      title: "Free Fire",
      description: "4v4 mobile shooter competition.",
      is_srm_only: true,
    },
    {
      id: 40,
      format: "PC",
      title: "Valorant",
      description: "5v5 PC tactical shooter event.",
      is_srm_only: true,
    },
    {
      id: 41,
      format: "Mobile",
      title: "Clash Royale",
      description: "1v1 real-time strategy card battle.",
      is_srm_only: false,
    },
  ],
  summary: {
    total_events: 41,
    events_for_srm_students: 19,
  },
};
